### ISSUE TITLE
string pattern matching

### ISSUE THREAD

**Issue by slifin** [HealthSamurai/matcho#5]
I thought I could use this:

```
(m/assert "abc" "abcd")
```

In the sense that I thought strings were collections of characters, but that doesn't work, is there a way to do string pattern matching with data using matcho?

**Comment by niquola** [comment]
You can use regexps
```clojure
(m/assert  #"^abc.*" "abcd")
```

**Comment by slifin** [comment]
Of course! 😅 Thank you
